---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linksys
  namespace: external
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: 'true'
    flame.pawelmalak/type: app
    flame.pawelmalak/name: linksys
    flame.pawelmalak/url: https://linksys.claytonc.dev
    flame.pawelmalak/icon: access-point-network
spec:
  tls:
  - hosts:
      - linksys.claytonc.dev
    secretName: linksys-tls
  rules:
    - host: linksys.claytonc.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  linksys
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: linksys
  namespace: external
spec:
  externalName: 192.168.1.1
  type: ExternalName
  ports:
  - protocol: TCP
    port: 80
