apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas
  namespace: external
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: 'true'
    flame.pawelmalak/type: app
    flame.pawelmalak/name: truenas
    flame.pawelmalak/url: https://nas.claytonc.dev
    flame.pawelmalak/icon: nas
spec:
  tls:
  - hosts:
      - nas.claytonc.dev
    secretName: truenas-tls
  rules:
    - host: nas.claytonc.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truenas
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: external
spec:
  externalName: 192.168.1.108
  type: ExternalName
  ports:
  - protocol: TCP
    port: 80
