apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
spec:
  destination:
    name: ''
    namespace: argo-events
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 1.13.0
    chart: argo-events
    helm:
      parameters:
        - name: singleNamespace
          value: 'false'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
