env:
  TZ: PT

ingress:
  main:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-external
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: filebrowser
      flame.pawelmalak/url: https://cloud.claytonc.dev
      # flame.pawelmalak/icon: https://raw.githubusercontent.com/filebrowser/filebrowser/master/frontend/public/img/logo.svg
      flame.pawelmalak/icon: file-multiple
    hosts:
      - host: cloud.claytonc.dev
        paths:
          - path: /
    tls: 
     - secretName: cloud-tls
       hosts:
         - cloud.claytonc.dev


config: |
  {
    "port": 80,
    "baseURL": "",
    "address": "",
    "log": "stdout",
    "database": "/config/database.db",
    "root": "/srv/data"
  }

persistence:
  config:
    enabled: true
    mountpath: /config
    retain: true
    #exisitingClaim: filebrowser-config


  data:
    enabled: true
    mountPath: /srv/data
    accessMode: ReadWriteMany
    retain: true
    #exisitingClaim: filebrowser-data
    type: pvc
    size: 10Gi
