env:
  TZ: PT

ingress:
  main:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-external
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: jellyfin
      flame.pawelmalak/url: https://jellyfin.claytonc.dev
      flame.pawelmalak/icon: play-network
    hosts:
      - host: jellyfin.claytonc.dev
        paths:
          - path: /
    tls: 
     - secretName: jellyfin-tls
       hosts:
         - jellyfin.claytonc.dev


persistence:
  config:
    enabled: true
    retain: true

  cache:
    enabled: false
    mountPath: /cache

  movies:
    enabled: true
    mountPath: /media/movies
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi

  shows:
    enabled: true
    mountPath: /media/shows
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi

  music:
    enabled: true
    mountPath: /media/music
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi