env:
  TZ: PT

ingress:
  main:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: lidarr
      flame.pawelmalak/url: https://music.claytonc.dev
      flame.pawelmalak/icon: music
    hosts:
      - host: music.claytonc.dev
        paths:
          - path: /
    tls: 
     - secretName: lidarr-tls
       hosts:
         - music.claytonc.dev

probes:
  liveness:
    enabled: false

persistence:
  config:
    enabled: true
    retain: true

  music:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi
    existingClaim: jellyfin-music
  
  downloads:
    enabled: true
    mountPath: /downloads
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi
    existingClaim: transmission-downloads

metrics:
  enabled: false
