env:
  TZ: PT
  META_TITLE: Clayton Castro
  META_DESCRIPTION: Clayton Castro Social Links
  META_AUTHOR: Clayton Castro
  THEME: Dark
  FAVICON_URL: https://pbs.twimg.com/profile_images/1476040487752527880/qjm42pYJ_200x200.jpg
  AVATAR_URL: https://pbs.twimg.com/profile_images/1476040487752527880/qjm42pYJ_200x200.jpg
  AVATAR_2X_URL: https://pbs.twimg.com/profile_images/1476040487752527880/qjm42pYJ_400x400.jpg
  AVATAR_ALT: Clayton Castro Profile Pic
  NAME: Clayton Castro
  BIO: lil homepage
  GITHUB: https://github.com/clanktron
  TWITTER: https://twitter.com/clank_blank
  LINKED_IN: https://linkedin.com/in/claytonc-dev
  SNAPCHAT: https://www.snapchat.com/add/clanktronc
  EMAIL: hello@claytonc.dev
  EMAIL_TEXT: Email
  # BUYMEACOFFEE: https://www.buymeacoffee.com/claytonc
  BUTTON_ORDER: GITHUB,LINKED_IN,TWITTER,SNAPCHAT,EMAIL
  FOOTER: Cheers!

ingress:
  main:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-external
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: littlelink
      flame.pawelmalak/url: https://claytonc.dev
      flame.pawelmalak/icon: link-variant
    hosts:
      - host: claytonc.dev
        paths:
          - path: /
    tls: 
     - secretName: littlelink-tls
       hosts:
         - claytonc.dev

