# nameOverride: "prometheus"
namespaceOverride: "monitoring"
# fullnameOverride: ""

alertmanager:
  enabled: true
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: alertmanager
      flame.pawelmalak/url: https://alert.claytonc.dev
      flame.pawelmalak/icon: alert-circle-outline
    path: /
    hosts:
      - alert.claytonc.dev
    tls: 
     - secretName: alert-tls
       hosts:
         - alert.claytonc.dev
  serviceMonitor:
    interval: "1m"
    selfMonitor: true

grafana:
  defaultDashboardsTimezone: PT
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-external
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: grafana
      flame.pawelmalak/url: https://grafana.claytonc.dev
      flame.pawelmalak/icon: chart-box-outline
    path: /
    hosts:
      - grafana.claytonc.dev
    tls: 
     - secretName: grafana-tls
       hosts:
         - grafana.claytonc.dev

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      provider:
        allowUiUpdates: true
      
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
      defaultDatasourceScrapeInterval: 15s


  additionalDataSources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-kube-prometheus-prometheus:9090/
    access: proxy
    isDefault: true
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy

  serviceMonitor:
    enabled: true
    path: "/metrics"
    interval: "10s"

prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: prometheus
      flame.pawelmalak/url: https://prometheus.claytonc.dev
      flame.pawelmalak/icon: fire
    path: /
    hosts:
      - prometheus.claytonc.dev
    tls: 
     - secretName: prometheus-tls
       hosts:
         - prometheus.claytonc.dev
    
  serviceMonitor:
    enabled: true
    path: "/metrics"
    interval: ""

  prometheusSpec:
    scrapeInterval: "10s"

kubeApiServer:
  enabled: true
  serviceMonitor:
    interval: "10s"

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    interval: "10s"

kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      interval: "5s"

prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true
      interval: "10s"