env:
  TZ: PT

ingress:
  main:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: radarr
      flame.pawelmalak/url: https://movies.claytonc.dev
      flame.pawelmalak/icon: movie-open
    hosts:
      - host: movies.claytonc.dev
        paths:
          - path: /
    tls: 
     - secretName: radarr-tls
       hosts:
         - movies.claytonc.dev

probes:
  liveness:
    enabled: false

persistence:
  config:
    enabled: true
    retain: true

  movies:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi
    existingClaim: jellyfin-movies
  
  downloads:
    enabled: true
    mountPath: /downloads
    accessMode: ReadWriteMany
    retain: true
    type: pvc
    size: 10Gi
    existingClaim: transmission-downloads

metrics:
  enabled: false

