
initContainers:
  custom-webui:
    name: custom-webui
    image: curlimages/curl:7.76.1
    command: ["/bin/sh", "-c", "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config" ]
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 568
      runAsGroup: 568

env:
  TZ: PT
  TRANSMISSION_WEB_HOME: /config/flood-for-transmission/
  TRANSMISSION_RPC_PASSWORD: CHANGEME
  TRANSMISSION_DOWNLOAD_DIR: /downloads/complete
  TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
  TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
  TRANSMISSION_WATCH_DIR_ENABLED: true
  TRANSMISSION_WATCH_DIR: /watch


ingress:
  main:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: 'true'
      flame.pawelmalak/type: app
      flame.pawelmalak/name: transmission
      flame.pawelmalak/url: https://downloads.claytonc.dev
      flame.pawelmalak/icon: download-lock
    hosts:
      - host: downloads.claytonc.dev
        paths:
          - path: /
    tls: 
     - secretName: transmission-tls
       hosts:
         - downloads.claytonc.dev

persistence:
  config:
    enabled: true
    mountPath: /config
    retain: true

  downloads:
    enabled: true
    mountPath: /downloads
    retain: true
    accessMode: ReadWriteMany
    size: 10Gi

  watch:
    enabled: true
    mountPath: /watch
    retain: true
    accessMode: ReadWriteMany
    size: 10Gi

