apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argo
spec:
  destination:
    name: ''
    namespace: gitlab
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.gitlab.io/'
    targetRevision: 6.0.1
    chart: gitlab
    helm:
      values: |-

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
