apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argo
spec:
  destination:
    name: ''
    namespace: jellyfin
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 1.3.2
    chart: jellyfin
    helm:
      values: |-

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
