apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-root-ca
spec:
  destination:
    name: ''
    namespace: linkerd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/linkerd
    repoURL: 'https://github.com/clanktron/kube-manifests'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
