apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: littlelink
  namespace: argo
spec:
  destination:
    name: ''
    namespace: littlelink
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 1.3.2
    chart: littlelink-server
    helm:
      values: |+


  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
