apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-internal
  namespace: argo
spec:
  destination:
    name: ''
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 10.20.1
    chart: traefik
    helm:
      values: |-
        ingressClass:
          enabled: true
          isDefaultClass: false
        
        ingressRoute:
          dashboard:
            enabled: false
            annotations: {}
            labels: {}
        
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            allowExternalNameServices: true
            allowEmptyServices: false
            ingressClass: traefik-crd-internal
        
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true
            allowEmptyServices: false
            ingressClass: traefik-internal
        
        logs:
          general:
            level: INFO
          access:
            enabled: true
            filters: {}
            fields:
              general:
                defaultmode: keep
              headers:
                defaultmode: keep

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
