---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  annotations:
    linkerd.io/inject: enabled

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-events
  namespace: argo-events
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`events.claytonc.dev`)
      kind: Rule
      middlewares:
        - name: traefik-local-whitelist@kubernetescrd
      services:
      - name: argo-rollouts-dashboard
        port: 3100
        # scheme: https
        # serversTransport: insecure-skip-verify
  tls:
    secretName: rollouts-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: events-tls
  namespace: argo-events
spec:
  secretName: events-tls
  privateKey:
    rotationPolicy: Always 
  dnsNames:
    - events.claytonc.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
