---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  # annotations:
  #   linkerd.io/inject: enabled

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  privateKey:
    rotationPolicy: Always 
  dnsNames:
    - longhorn.claytonc.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`longhorn.claytonc.dev`)
      kind: Rule
      services:
      - name: longhorn-frontend
        port: 80
  tls:
    secretName: longhorn-tls
