---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
  # annotations:
  #   linkerd.io/inject: enabled

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`vault.claytonc.dev`)
    services:
    - kind: Service
      name: vaultwarden
      port: 80
      responseForwarding:
        flushInterval: 1ms
  tls:
    secretName: vaultwarden-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  privateKey:
    rotationPolicy: Always 
  dnsNames:
    - vault.claytonc.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
